AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/EndAlignment:
  EnforcedStyleAlignWith: 'variable'
Layout/CaseIndentation:
  EnforcedStyle: 'end'
  IndentOneStep: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'
Lint/RequireParentheses:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods:
    - 'context' # rspec context block
    - 'describe' # rspec describe block
    - 'before' # rspec before block
    - 'draw' # Rails.application.routes.draw
Metrics/LineLength:
  Max: 120
  IgnoredPatterns:
    - '\A\s+#' # Comment-only lines
    - '\A\s+(it|expect|context)(\(?|\s?)' # rspec 'it(', 'it ', 'expect(', 'expect ', 'context(' and 'context '
Metrics/MethodLength:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: 'snake_case'
Rails/BulkChangeTable:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: false
Rails/Date:
  EnforcedStyle: 'strict'
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'
Style/RaiseArgs:
  EnforcedStyle: 'exploded'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'
